pipeline {
    environment {
        registry = 'yanishub/jenkins_docker'
        registryCredential = 'dockerhub_id'
        dockerImage = ''
    }
    agent any
    stages {
        stage('Cloning our Git') {
            steps {
                git 'https://github.com/Yanisb2003/Jenkins_Python'
            }
        }
        stage('Building our image') {
            steps {
                script {
                    sh 'docker build -t yanishub/jenkins_docker:3 .'
                }
            }
        }
        stage('Deploy our image') {
            steps {
                script {
                    docker.withRegistry('', registryCredential) {
                        dockerImage.push()
                    }
                }
            }
        }
        stage('Cleaning up') {
            steps {
                sh "docker rmi $registry:$BUILD_NUMBER"
            }
        }
    }
}
